# Generated by Django 2.2.24 on 2021-07-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='nacionality',
            new_name='nationality',
        ),
    ]
