# Generated by Django 2.2.24 on 2021-07-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='editorial',
            new_name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='relased_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
