# Generated by Django 2.2.24 on 2021-07-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='founded',
            new_name='founded_date',
        ),
    ]
