# Generated by Django 2.2.24 on 2021-07-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_auto_20210703_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='founded_date',
        ),
        migrations.AddField(
            model_name='publisher',
            name='founded_year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
